// React/src/App.tsx
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import FileUploader from 'devextreme-react/file-uploader';

function App(): JSX.Element {
  return (
    <div className="demo-container">
      <div className="file-uploader-block">
        <FileUploader
          id="file-uploader"
          multiple={true}
          uploadMode="useButtons"
          allowCanceling={true}
          accept="image/*"
          labelText="Drop Images Below to Upload..."
          maxFileSize={32000000}
          dropZone=".file-uploader-block"
        />
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ClickEvent } from 'devextreme/ui/button';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    standalone: false
})
export class AppComponent {
  title = 'Angular';

  counter = 0;

  buttonText = 'Click count: 0';

  onClick(e: ClickEvent): void {
    this.counter++;
    this.buttonText = `Click count: ${this.counter}`;
  }
}

<div class="demo-container">
  <div class="file-uploader-block">
    <dx-file-uploader
      id="file-uploader"
      [multiple]="true"
      uploadMode="useButtons"
      [allowCanceling]="true"
      accept="image/*"
      labelText="Drop Images Here to Upload..."
      [maxFileSize]="32000000"
      dropZone=".file-uploader-block"
    ></dx-file-uploader>
  </div>
</div>
